### ISSUE TITLE
Failing job on staging - ShopperStatusController:83

### ISSUE THREAD

**Issue by abbood** [totersapp/asana-integration-test#3]
# Business Value Added
Fix potential issue before it reaches production

# Analysis
Got the logs from staging:

```
[2017-12-14 15:50:27] staging.ERROR: ErrorException: Creating default object from empty value in /home/forge/default/envoyer/releases/20171212131828/app/Http/Controllers/ShopperStatusController.php:83 Stack trace: #0 /home/forge/default/envoyer/releases/20171212131828/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Creating defaul...', '/home/forge/def...', 83, Array) #1 /home/forge/default/envoyer/releases/20171212131828/app/Http/Controllers/ShopperStatusController.php(83): Raven_Breadcrumbs_ErrorHandler->handleError(2, 'Creating defaul...', '/home/forge/def...', 83, Array) #2 [internal function]: App\Http\Controllers\ShopperStatusController->update(Object(Dingo\Api\Http\Request)) #3 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array) #4 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('update', Array) #5 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\ShopperStatusController), 'update') #6 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController() #7 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Dingo\Api\Http\Request)) #8 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request)) #9 /home/forge/default/envoyer/releases/20171212131828/app/Http/Middleware/RoleAuthMiddleware.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request)) #10 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\RoleAuthMiddleware->handle(Object(Dingo\Api\Http\Request), Object(Closure), 'shopper') #11 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #12 /home/forge/default/envoyer/releases/20171212131828/vendor/dingo/api/src/Http/Middleware/Auth.php(55): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request)) #13 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Dingo\Api\Http\Middleware\Auth->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #14 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #15 /home/forge/default/envoyer/releases/20171212131828/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request)) #16 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Dingo\Api\Http\Middleware\PrepareController->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #17 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #18 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Dingo\Api\Http\Request)) #19 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #20 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Dingo\Api\Http\Request)) #21 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Dingo\Api\Http\Request)) #22 /home/forge/default/envoyer/releases/20171212131828/vendor/dingo/api/src/Routing/Adapter/Laravel.php(81): Illuminate\Routing\Router->dispatch(Object(Dingo\Api\Http\Request)) #23 /home/forge/default/envoyer/releases/20171212131828/vendor/dingo/api/src/Routing/Router.php(513): Dingo\Api\Routing\Adapter\Laravel->dispatch(Object(Dingo\Api\Http\Request), 'v1') #24 /home/forge/default/envoyer/releases/20171212131828/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request)) #25 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request)) #26 /home/forge/default/envoyer/releases/20171212131828/app/Http/Middleware/LogMiddleware.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #27 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\LogMiddleware->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #28 /home/forge/default/envoyer/releases/20171212131828/app/Http/Middleware/CorsMiddleware.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #29 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\CorsMiddleware->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #30 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #31 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #32 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #33 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #34 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #35 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #36 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #37 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #38 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #39 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #40 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request)) #41 /home/forge/default/envoyer/releases/20171212131828/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #42 /home/forge/default/envoyer/releases/20171212131828/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request)) #43 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Dingo\Api\Http\Middleware\Request->handle(Object(Dingo\Api\Http\Request), Object(Closure)) #44 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #45 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #46 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #47 /home/forge/default/envoyer/releases/20171212131828/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #48 /home/forge/default/envoyer/releases/20171212131828/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #49 {main} [] []
```

The error message is:

ErrorException: Creating default object from empty value in ShopperStatusController:83

# Steps to fix
1. Manually delete or fix abdullah's shopper on staging :white_check_mark:
2. Make sure the fix worked
3. write explanation of the issue

**Comment by abbood** [comment]
➤ Tamim Al Khalfah commented:

What is this  [~abdullah] ?
